### PR TITLE
Enable build on windows

### PR DESCRIPTION
**Pull request by sthiele**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by druvus** [comment]
@conda-forge-admin, please rerender

**Comment by sthiele** [comment]
Let me know if there is anyway I can help with this.

**Comment by druvus** [comment]
@conda-forge-admin, please rerender

**Comment by druvus** [comment]
@conda-forge-admin, please restart ci

**Comment by druvus** [comment]
sorry this slipped between the cracks... seems it trying to use gcc so I need to take a look at the upstream code.

**Comment by Midnighter** [comment]
This is blocking me from making a cobrapy conda-forge package. Would love to help move this along. Swiglpk itself builds windows wheels so this should definitely be possible.

**Comment by Midnighter** [comment]
I guess the key elements are in https://github.com/biosustain/swiglpk/blob/master/appveyor.yml and https://github.com/biosustain/swiglpk/blob/master/appveyor/build_glpk.py so there may need to be a separate install script for windows.

**Comment by sthiele** [comment]
@Midnighter I'm not very conda savy, but i think you mean we need a `build.sh` and `build.bat`. I guess the content of `build.sh` would be 

```sh
#!/bin/bash
alias gcc="${CC}"; 
$PYTHON -m pip install . --no-deps -vv
```
Can someone deduce from the appveyor file how the `build.bat` could look like?

**Comment by Midnighter** [comment]
Hmm, I played around with this recipe for a while on a Windows system and I think the swiglpk setup is simply not very friendly. I am tempted to create a whole new package based on [CFFI](https://cffi.readthedocs.io) rather than SWIG but I seriously lack time at the moment. Would also have to make sure that optlang will be happy with the changes so it's quite an effort.

**Comment by cdiener** [comment]
Yeah that would be a lot of work. There is some custom code added as well that would need to be ported. Do you have a branch with your attempts? Conda-forge does have a MSVC setup and make so it should work with similar steps as on app store. If the buuld_glpk.py is the problem we could also try with the conda package for that.

**Comment by Midnighter** [comment]
> There is some custom code added as well that would need to be ported.

Are you referring to https://github.com/biosustain/swiglpk/blob/db54754a47f7d4748fe87e590390e6036343dc6e/setup.py#L34-L42 since that seems to be SWIG specific I was hoping the problem would simply go away with CFFI :stuck_out_tongue: 

> Do you have a branch with your attempts?

No, I just made some local attempts on a Windows machine to install swiglpk from the source package but I did not succeed even when installing GLPK from conda-forge. Since swiglpk already loads GLPK and GMP in its package build phase, I think it should simply redistribute those source files for the swiglpk sdist. Then there would be no need to provide those again.

> Conda-forge does have a MSVC setup and make so it should work with similar steps as on app store. If the `build_glpk.py` is the problem we could also try with the conda package for that.

That is good to know. I simply downloaded https://files.pythonhosted.org/packages/0e/c9/9b0ec3e2ca942b6d067e84e52d72818fa9c3a1a1524671fcbec4841b54b2/swiglpk-4.65.1.tar.gz since that is what the conda-forge build process does. You will see that there is no `build_glpk.py` in the archive. That's why I think the way to go would be to include GLPK and GMP sources.

**Comment by cdiener** [comment]
Thanks for the quick reply. with custom code I was referring to https://github.com/biosustain/swiglpk/blob/master/swiglpk/glpk.i#L70-L184 which gets the primals and duals. This is not part of the standard glpk.

I agree that it should use the libs from conda for glpk. I think gmp is statically linked into glpk so we should not have to worry about it. You probably have to add some fixes since the swiglpk setup.py assumes the wrong locations for glpk.h and glpk.lib for conda. The glpk conda-forge package comes with a test python package that shows where all of that should be found (https://github.com/conda-forge/glpk-feedstock/blob/master/recipe/setup.py). So one would either have to adjust the swiglpk.py to use those locations when building on conda-forge or maybe it would be enough to just copy those files to the required locations before build. Happy to help out or look over error messages.

**Comment by Midnighter** [comment]
> Happy to help out or look over error messages.

Since this is blocking a cobrapy conda-forge package and I don't have regular access to a Windows machine, I'd appreciate any help that you can lend on this topic.

**Comment by druvus** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
